### ISSUE TITLE
[Bug Report] The username section on the bottom left is misaligned and cramped

### ISSUE THREAD

**Issue by mcspidey95** [CreArts-Community/CreArts-Discord#35]
**Describe the bug**
The username section seems to have misalligned and cramped to the left. (visual in screenshot)

**To Reproduce**
Nothing, is seen when discord is opened.

**Expected behaviour**
The section should be alligned in the center and take up the whole space like it used to.

**Screenshots**
Screenshot attached below.

**Operating System:**
Which operating system do you use?

- [ ] Linux
- [X ] Windows
- [ ] macOS

**Additional context**
![Screenshot_111](https://user-images.githubusercontent.com/90018162/183949661-d7ceaa8d-e86d-4600-a945-c12d0ca7462a.png)

**Comment by CorellanStoma** [comment]
This should fix it:

```css
.container-YkUktl:not(.powercord-spotify .container-YkUktl) .avatarWrapper-1B9FTW {
  grid-column: 1 / span 2;
}

.container-YkUktl:not(.powercord-spotify .container-YkUktl) .withTagAsButton-OsgQ9L, .withTagless-10ooWt {
  min-width: unset !important;
}

.container-YkUktl:not(.powercord-spotify .container-YkUktl) .nameTag-sc-gpq {
  background: transparent;
  position: relative;
  margin: 0px;
  left: 8px;
}
```
